### ISSUE TITLE
Links under "What is jsPerf" use incorrect directory. 

### ISSUE THREAD

**Issue by ChildishGiant** [TwitchBronBron/jsperf-static#1]
The test cases and FAQ links both use the root of your GitHub domain, not the local file. This ends up with a 404.

**Comment by TwitchBronBron** [comment]
Thanks. I believe I have fixed them both just now. Give it a try, let me know if that works for you now. 

The "test cases" is now just a section on the index page showing any locally-saved test cases. I don't have access to the jsperf database, so they're all saved in local storage. Here's what it looks like: 

![image](https://user-images.githubusercontent.com/2544493/141790153-f1cbc47e-ff2f-4fef-8aad-31ff2fe50a1d.png)
